site_name: RCJ Soccer 2022
theme:
  name: material
  palette:
    primary: green

nav:
  - Home: index.md
  - Code Submission: "code-submission.md"
  - Submission check: "submission-check.md"
  - SoccerSim Demo Competition 2022: "demo-competition-2022.md"
  - SoccerSim World Championship 2022: "world-competition.md"
  - "SoccerSim Demo Competition 2022 Results":
    - "Group Phase": "demo/demo-2022-group-phase.md"
    - "Quarter Finals": "demo/demo-2022-quarter-finals.md"
    - "Semifinals": "demo/demo-2022-semifinals.md"
    - "Finals": "demo/demo-2022-finals.md"
  - "SoccerSim World Championship 2022 Results":
    - "Technical Challenge Results": "world/tech-challenges.md"
    - "Team Description Papers": "world/tdps.md"
    - "Games - Round 1": "world/round1.md"
    - "Games - Round 2": "world/round2.md"
  - SoccerSim Code Submission: "code-submission.md"
